const logData = [
  {
    id: 1,
    date: '16.08.2021',
    time: '13:48',
    duration: '48',
    country: 'Egypt',
    spot: 'Abu Nashim',
    airStart: '200',
    airEnd: '60',
    airEan: '32',
    waterDepthMax: '28.4',
    waterDepthAvg: '17.3',
    waterTemp: '23',
    notes: 'Nice corals in the red sea!',
    buddy: 'Antonia',
  },
  {
    id: 2,
    date: '17.08.2021',
    time: '11:12',
    duration: '35',
    country: 'Tenerife',
    spot: 'Shark Bay',
    airStart: '220',
    airEnd: '70',
    airEan: '30',
    waterDepthMax: '35.3',
    waterDepthAvg: '20.3',
    waterTemp: '21',
    notes:
      'Tenerife is not only a nice island. Also the ocean around has a lot ot offer :)',
    buddy: 'Dirk',
  },
  {
    id: 3,
    date: '20.09.2021',
    time: '06:00',
    duration: '50',
    country: 'Germany',
    spot: 'Hemmoor',
    airStart: '210',
    airEnd: '45',
    airEan: '21',
    waterDepthMax: '41.5',
    waterDepthAvg: '25.4',
    waterTemp: '6',
    notes:
      'Yeah, German seas are very cold! I would recommend a dry suit next time!',
    buddy: 'Heinz',
  },
];
export { logData };
